
DROP DATABASE WellTimed;

CREATE DATABASE WellTimed;
USE WellTimed;

CREATE TABLE Users(
	UserID INT AUTO_INCREMENT NOT NULL,
	UserName VARCHAR(50) NOT NULL UNIQUE,
	JoinedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP  NOT NULL,
	LastModifiedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,

	PRIMARY KEY (UserID)
	);


CREATE TABLE Events(
	EventID INT AUTO_INCREMENT NOT NULL,
	EventName VARCHAR(50) NOT NULL UNIQUE,
	CreatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP  NOT NULL,
	LastModifiedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	EventDescription VARCHAR(240),
	EventDATETIME DATETIME NOT NULL,
	EventDuration FLOAT, -- negetive for all day event
	EventCreator INT NOT NULL,
	FOREIGN KEY (EventCreator) REFERENCES Users(UserID),
	PRIMARY KEY (EventID)
	);

CREATE TABLE EventAttendees(
	AttendeesID INT AUTO_INCREMENT NOT NULL,
	UserID INT NOT NULL,
	EventID INT NOT NULL,

	PRIMARY KEY (AttendeesID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
	FOREIGN KEY (EventID) REFERENCES Events(EventID)
	);


INSERT INTO Users (UserName)VALUES('Louie');

INSERT INTO Users (UserName)VALUES('Louie');